name: CI Notice

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      
      - uses: actions-cool/ci-notice@main
        with:
          ci: |
            npm install
            npm run package
          notice-types: 'issue'
          issue-assignees: 'xrkffgg'
